cart_app/urls.py
from django.urls import path
from . import views

# from cart_app .views import (

# )


app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),

    path('add/', views.cart_add, name='cart_add'),
    path('update/', views.cart_update, name='cart_update'),
    path('delete/', views.cart_delete, name='cart_delete'),
]

nft_ecommerce_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profile_app.urls')),
    path('', include('store_app.urls', namespace='store')),
    path('cart/', include('cart_app.urls', namespace='cart')),
    path('accounts/', include('allauth.urls')),
]

# handler403 = "board_app.views.access_denied"
# handler400 = "board_app.views.bad_request"
# handler404 = "board_app.views.page_not_found_view"
# handler500 = "board_app.views.handler500"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

profile_app/urls.py
from django.urls import path
# from . import views


from profile_app .views import (
    ProfileListView
)


urlpatterns = [
    path('', ProfileListView.as_view(), name='profile'),
    # path('', ProfileListView.as_view(), name='profile'),
]

store_app/urls.py
from django.urls import path
from . import views

from store_app .views import (
    HomeListView,
    ProductDetailView,
    # CreateCheckoutSessionView,
    # SuccessView, CancelView
)
app_name = 'store'


urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('product/<slug:slug>/', ProductDetailView.as_view(),
         name='product_detail',),
    path('search/<slug:category_slug>/',
         views.category_list, name='category_list'),



    # path('', views.home, name='home'),
    # path('create-checkout-session/', CreateCheckoutSessionView.as_view(),
    #      name='create-checkout-session'),

    # path('checkout/', views.checkout, name='checkout'),

    # path('success/', SuccessView.as_view(), name='success'),
    # path('cancel/', CancelView.as_view(), name='cancel'),

]

cart_app/models.py
from django.db import models

# Create your models here.

profile_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from PIL import Image


# from store_app.models import Product


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)

    image = models.ImageField(
        default='default.jpg', upload_to='profile_pics')
    date_joined = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.user.username} Profile'

store_app/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.text import slugify


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse('board_app:category_list', args=[self.slug])

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class Product(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(null=True, blank=True, upload_to='product_pics')
    description = models.CharField(max_length=300)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="post_author")

    stripe_product_id = models.CharField(max_length=100)
    slug = models.SlugField(max_length=250, unique=True)
    date_posted = models.DateTimeField(default=timezone.now, editable=False)
    category = models.ForeignKey(
        Category, related_name='product', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=4, decimal_places=2, null=True)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)

    products = ProductManager()

    class Meta:
        ordering = ('-date_posted',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('store:product_detail', kwargs={'slug': self.slug})
    # def category_name(self):
    #     all = []
    #     for a in self.category.all():
    #         all.append(str(a))
    #     return "; ".join(all)

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

cart_app/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from store_app.models import Product
from .cart import Cart


def cart_summary(request):
    cart = Cart(request)
    return render(request, 'store_app/cart/cart.html', {'cart': cart})


def cart_add(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product, qty=product_qty)

        cartqty = cart.__len__()
        carttotal = cart.get_total_price()

        # response = JsonResponse({'qty': cartqty})
        response = JsonResponse({'qty': cartqty, 'subtotal': carttotal})

        return response


def cart_update(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        cart.update(product=product_id, qty=product_qty)
        # print(product_id)
        # print(product_qty)
        cartqty = cart.__len__()
        carttotal = cart.get_total_price()
        # total = cart.total_price()

        response = JsonResponse(
            {'qty': cartqty, 'subtotal': carttotal})
        # response = JsonResponse({'Success': True})
        return response


def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        cart.delete(product=product_id)
        cartqty = cart.__len__()
        carttotal = cart.get_total_price()

        response = JsonResponse({'qty': cartqty, 'subtotal': carttotal})
        return response

profile_app/views.py
from django.shortcuts import render
from store_app.models import Product
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import (
    ListView,
)


class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    username = User.username
    template_name = 'profile_app/profile_page.html'
    context_object_name = 'posts'

store_app/views.py
from django.shortcuts import redirect, render, get_object_or_404

from store_app.models import Product, Category
from profile_app.models import Profile
# from django.views import generic

from django.views.generic import (
    ListView,
    DetailView,
)


class HomeListView(ListView):
    model = Product
    template_name = 'store_app/home.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.products.all()


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.products.filter(category=category)

    context = {
        'category': category,
        'products': products,
    }
    return render(request, 'store_app/category.html', context)


class ProductDetailView(DetailView):
    model = Product

store_app/templates/store_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- tailwind css -->
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- my navbar + nav dropdown -->
    <script src="../../static/store_app/js/navbar.js"></script>
    <!-- jquery minified -->
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"
        integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <!-- stripe -->
    <!-- <script src="https://js.stripe.com/v3/"></script> -->


    {% block extra_head %}

    {% endblock extra_head %}


    <script src="https://unpkg.com/@themesberg/flowbite@latest/dist/flowbite.bundle.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'store_app/css/style.css' %}">
    <title>DIGITAL-ART{% block head_title %}{% endblock %}</title>
</head>


<body>

    {% comment %}
    {% endcomment %}
    {% include 'store_app/components/navbar.html' %}



    <div class="">
        {% block content %}{% endblock content %}
    </div>

    {% block extra_body %}
    {% endblock extra_body %}

    <script>
        $(document).ready(function () {
            $('.add-button').click(function (e) {
                e.preventDefault();
                var productId = $(this).data('index');
                //var productQty = $("#select" + productId + "option:selected").val();
                var productQty = $('#select option:selected').val();
                var csrfToken = "{{ csrf_token }}";

                $.ajax({
                    type: 'POST',
                    url: '{% url "cart:cart_add" %}',
                    data: {
                        productid: productId,
                        productqty: productQty,
                        csrfmiddlewaretoken: csrfToken,
                        action: "post"
                    },
                    success: function (json) {
                        $('#cart-qty').html(json.qty);
                        console.log(json);
                    },
                    error: function (xhr, errmsg, err) {
                        console.log(errmsg);
                    }
                });
            });
        });
    </script>

</body>

</html>

store_app/templates/store_app/cancle.html
{% extends 'store_app/base.html' %}

{% block extra_head %}
<script src="https://js.stripe.com/v3/"></script>
{% endblock extra_head %}

{% block head_title %} : Home{% endblock %}

{% load static %}

{% block content %}

<section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
</section>

{% endblock content %}

store_app/templates/store_app/cart/cart.html
{% extends '../base.html' %}

{% block extra_head %}
<script src="https://js.stripe.com/v3/"></script>
{% endblock extra_head %}

{% block head_title %} : Cart{% endblock %}

{% load static %}

{% block content %}


<div class="mx-auto flex justify-center pt-32 ">
    <div class="w-full md:w-2/3 2xl:w-1/2 px-4">
        <h4 class="text-4xl mb-8">My Cart</h4>
        <ul role="list" class="">
            {% for item in cart %}
            {% with product=item.product %}
            <li data-index="{{product.id}}" class="product-item py-4 md:py-6 border-b border-gray-300">
                <div class="flex space-x-4">
                    <a href="{{ product.get_absolute_url }}">
                        <img class="rounded object-cover  w-24" src="{{product.image.url}}" alt="" />
                    </a>
                    <div class="flex-1 min-w-0">
                        <h4 class="mb-2 text-3xl font-bold tracking-tight text-gray-900">
                            {{product.title}}
                        </h4>
                        <!-- <p class="">Quantity: {{item.qty}}</p> -->
                        <form id="checkout-form" action="/create-checkout-session" method="POST">
                            <div class="flex">
                                <div class="w-24">
                                    <label for="select">Qty</label>
                                    <select id="select{{product.id}}"
                                        class="mt-2 bg-white border border-gray-300 text-gray-800 rounded-md focus:ring-fuchsia-500 focus:border-fuchsia-500 block py-2 px-3">
                                        <option selected>{{item.qty}}</option>
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                        <option value="6">6</option>
                                    </select>
                                </div>
                                <div class="flex items-end text-gray-600 text-3xl">
                                    <button type="button" id="update-button" value="{{product.id}}"
                                        data-index="{{ product.id }}"
                                        class="update-button text-base text-slate-500 hover:text-fuchsia-500">Update</button>
                                    <button type="button" id="delete-button" value="{{product.id}}"
                                        data-index="{{ product.id }}"
                                        class="delete-button ml-4 text-base text-slate-500 hover:text-fuchsia-500">Delete</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="flex items-end text-gray-900">
                        <div>
                            <!-- <p>Price: <strong>€{{item.price}}</strong></p>
                            <p>Sub-total: <strong>€{{item.total_price}}</strong></p> -->
                            <p id="total">Price: <strong>€{{item.price}}</strong></p>
                        </div>
                    </div>
                </div>
            </li>
            {% endwith %}
            {% endfor %}
        </ul>
        <div class="flex flex-row-reverse mt-6">
            <div class="text-end">

                <h4>Sub-total: <strong>€<span id="subtotal" class="subtotal">{{ cart.get_total_price }}</span></strong>
                </h4>

                <form action="POST">
                    {% csrf_token %}
                    <button type="button"
                        class=" min-w-full block mt-10 bg-fuchsia-600 hover:bg-fuchsia-500 text-white font-bold px-8 py-2  border-b-4 border-fuchsia-800 hover:border-fuchsia-600 rounded">
                        Checkout
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- script -->
<script>
    $(document).ready(function () {
        $('.delete-button').click(function (e) {
            e.preventDefault();
            var productId = $(this).data('index');
            var csrfToken = "{{ csrf_token }}";
            $.ajax({
                type: 'POST',
                url: '{% url "cart:cart_delete" %}',
                data: {
                    productid: productId,
                    csrfmiddlewaretoken: csrfToken,
                    action: "post"
                },
                success: function (json) {
                    $('.product-item[data-index="' + productId + '"]').remove();
                    document.getElementById('subtotal').innerHTML = json.subtotal
                    document.getElementById('cart-qty').innerHTML = json.qty

                    //    console.log(json);
                },
                error: function (xhr, errmsg, err) {
                    console.log(errmsg);
                }
            });
        });
        // update item
        $('.update-button').click(function (e) {
            e.preventDefault();
            var productId = $(this).data('index');
            var productQty = $('#select' + productId + ' option:selected').val();

            var csrfToken = "{{ csrf_token }}";
            $.ajax({
                type: 'POST',
                url: '{% url "cart:cart_update" %}',
                data: {
                    productid: productId,
                    productqty: productQty,
                    csrfmiddlewaretoken: csrfToken,
                    action: "post"
                },
                success: function (json) {
                    document.getElementById('cart-qty').innerHTML = json.qty
                    document.getElementById('subtotal').innerHTML = json.subtotal
                    //document.getElementById('total').innerHTML = json.total
                    //document.getElementsByClassName('subtotal').innerHTML = json.subtotal
                    //            $('.product-item[data-index="' + productId + '"]').remove();
                    //    console.log(json);
                },
                error: function (xhr, errmsg, err) {
                    console.log(errmsg);
                }
            });
        });
    });
</script>

{% endblock content %}

store_app/templates/store_app/category.html
{% extends 'store_app/base.html' %}

{% block extra_head %}
<script src="https://js.stripe.com/v3/"></script>
{% endblock extra_head %}

{% block head_title %} : {{ page_title }}{% endblock %}

{% load static %}

{% block content %}

<div class="max-w-screen-2xl mx-auto grid md:grid-cols-2 gap-4 pt-20 px-4">
    {% for product in products %}
    <section class="flex justify-center">
        <div class="product max-w-sm bg-white border border-gray-200 rounded-lg shadow">
            <a href="{{ product.get_absolute_url }}">
                <img class="rounded-t-lg w-96 h-56 object-cover" src="{{ product.image.url }}" alt="" />
            </a>
            <div class="p-4">
                <div class="description pb-4">
                    <h5 class="text-2xl font-bold tracking-tight text-slate-800">{{ product.title }}
                    </h5>
                    <div class="mb-5 md:mb-0 text-slate-600">
                        <p class="mb-2 tracking-tight">{{ product.description }}</p>

                        <p class="text-sm mt-12 mb-4">
                            <strong>Artist:</strong>
                            <span>{{product.author}}</span>
                        </p>
                        <h5 class="text-slate-800 text-xl">€{{ product.price }}</h5>
                    </div>
                </div>
                <!-- <form id="checkout-form" action="/create-checkout-session" method="POST">
                    <div class="flex">
                        <div class="w-24">
                            <label for="select">Qty</label>
                            <select id="select" data-index="product.id"
                                class="select mt-2 bg-white border border-gray-300 text-gray-800 rounded-md focus:ring-fuchsia-500 focus:border-fuchsia-500 block py-2 px-3">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                            </select>
                        </div>
                    </div>
                    <button type="button" id="update-button" value="{{product.id}}" data-index="{{ product.id }}"
                        class="add-button mt-6 bg-fuchsia-600 hover:bg-fuchsia-500 text-white font-bold py-2 px-4 border-b-4 border-fuchsia-800 hover:border-fuchsia-600 rounded">
                        Add to Cart
                    </button>
                </form> -->
            </div>
        </div>
    </section>
    {% endfor %}
</div>

{% endblock content %}

store_app/templates/store_app/components/navbar.html
{% load static %}

<nav class="bg-white border-gray-200 md:px-4 xl:px-6">
    <div class="max-w-screen-2xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="{% url 'store:home' %}" class="flex items-center">
            <img src="{% static 'store_app/icons/black_logo.svg' %}" class="h-8 mr-3" alt="Flowbite Logo" />
            <span class="self-center text-2xl font-semibold whitespace-nowrap text-slate-800">DIGITAL-ART</span>
        </a>
        <div class="flex items-center sm:order-2">
            <div class="pr-6">
                <span class="relative">
                    <a href="{% url 'cart:cart_summary' %}" class="flex">

                        <!-- <p id="cart-price" class="pr-2 text-slate-800" id="subtotal" class="subtotal">

                            {% if cart.get_total_price %}
                            €{{ cart.get_total_price }}
                            {% else %}
                            empty
                            {% endif %}


                        </p> -->

                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="26" height="26">
                            <path
                                d="M4.00488 16V4H2.00488V2H5.00488C5.55717 2 6.00488 2.44772 6.00488 3V15H18.4433L20.4433 7H8.00488V5H21.7241C22.2764 5 22.7241 5.44772 22.7241 6C22.7241 6.08176 22.7141 6.16322 22.6942 6.24254L20.1942 16.2425C20.083 16.6877 19.683 17 19.2241 17H5.00488C4.4526 17 4.00488 16.5523 4.00488 16ZM6.00488 23C4.90031 23 4.00488 22.1046 4.00488 21C4.00488 19.8954 4.90031 19 6.00488 19C7.10945 19 8.00488 19.8954 8.00488 21C8.00488 22.1046 7.10945 23 6.00488 23ZM18.0049 23C16.9003 23 16.0049 22.1046 16.0049 21C16.0049 19.8954 16.9003 19 18.0049 19C19.1095 19 20.0049 19.8954 20.0049 21C20.0049 22.1046 19.1095 23 18.0049 23Z"
                                fill="#333333"></path>
                        </svg>
                        {% with total_qty=cart|length %}
                        <span id="cart-qty"
                            class="absolute top-0 right-0 inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-red-100 transform translate-x-1/2 -translate-y-1/2 bg-red-600 rounded-full">
                            {% if total_qty > 0 %}
                            {{total_qty}}
                            {% else %}
                            0
                            {% endif %}
                        </span>
                        {% endwith %}
                    </a>
                </span>
            </div>

            <button type="button"
                class="flex mr-3 text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 "
                id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown"
                data-dropdown-placement="bottom">
                <span class="sr-only">Open user menu</span>
                <img class="w-10 h-10 rounded-full border-none" src="{{user.profile.image.url}}" alt="user photo">
            </button>
            <!-- Dropdown menu -->
            <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow"
                id="user-dropdown">
                <div class="px-4 py-3">
                    <span class="block text-sm text-gray-900">{{user.username}}</span>
                    <span class="block text-sm  text-gray-500 truncate ">{{user.email}}</span>
                </div>
                <ul class="py-2" aria-labelledby="user-menu-button">
                    <li>
                        <a href="{% url 'profile' %}"
                            class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Dashboard</a>
                    </li>
                    <li>
                        <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Orders</a>
                    </li>
                    <li>
                        <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Wishlist</a>
                    </li>
                    <li>
                        <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Addresses</a>
                    </li>
                    <li>
                        <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Settings</a>
                    </li>
                </ul>
                <div class="py-1">
                    <a href="{% url 'account_logout' %}"
                        class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Sign
                        out</a>
                </div>
            </div>
            <button data-collapse-toggle="mobile-menu-2" type="button"
                class="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 "
                aria-controls="mobile-menu-2" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                        clip-rule="evenodd"></path>
                </svg>
            </button>
        </div>
        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="mobile-menu-2">
            <ul
                class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white ">
                <li>
                    <a href="#"
                        class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 ">About</a>
                </li>
                <li>
                    <a href="#"
                        class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 ">Services</a>
                </li>
                <li>
                    <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavbar"
                        class="flex items-center justify-between w-full py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:w-auto">Art
                        <svg class="w-5 h-5 ml-1" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                clip-rule="evenodd"></path>
                        </svg>
                    </button>
                    <!-- Dropdown menu -->
                    <div id="dropdownNavbar"
                        class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44 ">
                        <ul class="py-2 text-sm text-gray-700 " aria-labelledby="dropdownLargeButton">

                            {% for c in categories %}
                            <li>
                                <a class="block px-4 py-2 hover:bg-gray-100"
                                    href="/search/{{ c.slug }}">{{ c.name|title }}</a>
                            </li>
                            {% endfor %}

                        </ul>
                    </div>
                </li>
                <li>
                    <a href="#"
                        class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 ">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

store_app/templates/store_app/home.html
{% extends 'store_app/base.html' %}

{% block extra_head %}
{% endblock extra_head %}

{% block head_title %} : Home{% endblock %}

{% load static %}

{% block content %}


<div class="max-w-screen-2xl mx-auto grid md:grid-cols-2 gap-4 pt-20 px-4">
    {% for product in products %}
    <section class="flex justify-center">
        <div class="product max-w-sm bg-white border border-gray-200 rounded-lg shadow">
            <a href="{{ product.get_absolute_url }}">
                <img class="rounded-t-lg w-96 h-56 object-cover" src="{{ product.image.url }}" alt="" />
            </a>
            <div class="p-4">
                <div class="description pb-4">
                    <h5 class="text-2xl font-bold tracking-tight text-slate-800">{{ product.title }}
                    </h5>
                    <div class="mb-5 md:mb-0 text-slate-600">
                        <p class="mb-2 tracking-tight">{{ product.description }}</p>

                        <p class="text-sm mt-12 mb-4">
                            <strong>Artist:</strong>
                            <span>{{product.author}}</span>
                        </p>
                        <h5 class="text-slate-800 text-xl">€{{ product.price }}</h5>
                    </div>
                </div>
                <!-- <form id="checkout-form" action="/create-checkout-session" method="POST">
                    <div class="flex">
                        <div class="w-24">
                            <label for="select">Qty</label>
                            <select id="select" data-index="product.id"
                                class="select mt-2 bg-white border border-gray-300 text-gray-800 rounded-md focus:ring-fuchsia-500 focus:border-fuchsia-500 block py-2 px-3">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                            </select>
                        </div>
                    </div>
                    <button type="button" id="update-button" value="{{product.id}}" data-index="{{ product.id }}"
                        class="add-button mt-6 bg-fuchsia-600 hover:bg-fuchsia-500 text-white font-bold py-2 px-4 border-b-4 border-fuchsia-800 hover:border-fuchsia-600 rounded">
                        Add to Cart
                    </button>
                </form> -->
            </div>
        </div>
    </section>
    {% endfor %}
</div>

{% endblock content %}

store_app/templates/store_app/success.html
{% extends 'store_app/base.html' %}

{% block extra_head %}
<script src="https://js.stripe.com/v3/"></script>
{% endblock extra_head %}

{% block head_title %} : Home{% endblock %}

{% load static %}

{% block content %}

<section>
    <p>
        We appreciate your business! If you have any questions, please email
        <a href="mailto:orders@example.com">orders@example.com</a>.
    </p>
</section>







{% endblock content %}